In [97]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [98]:
data = yf.download('HDFCBANK.NS', start='2018-01-01', end='2023-12-31',interval="1d")

[*********************100%%**********************]  1 of 1 completed

In [99]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2018-01-01,936.349976,940.375000,925.250000,927.250000,889.052124,3290258
2018-01-02,929.275024,937.500000,929.275024,936.174988,897.609497,2388158
2018-01-03,937.500000,939.125000,925.599976,926.325012,888.165283,2265644
2018-01-04,926.500000,932.750000,926.500000,929.950012,891.640991,1186888
2018-01-05,931.500000,934.025024,927.775024,931.799988,893.414795,1435434
...,...,...,...,...,...,...
2023-12-22,1683.599976,1685.900024,1667.099976,1670.849976,1670.849976,24289425
2023-12-26,1673.250000,1685.949951,1668.550049,1682.449951,1682.449951,9022928
2023-12-27,1681.500000,1706.500000,1678.599976,1703.300049,1703.300049,13504539
2023-12-28,1709.300049,1721.400024,1702.000000,1705.250000,1705.250000,22038235
2023-12-29,1697.000000,1714.900024,1696.000000,1709.250000,1709.250000,12505713

In [100]:
data['Tick_Size'] = data['High'] - data['Low']

In [101]:
import allTechnicalIndicators as ti

In [102]:

# Calculate Simple Moving Averages (SMA)
short_ma=ti.sma_20(data['Close'])
data['Short_MA'] =short_ma
long_ma =ti.sma_50(data['Close'])
data['Long_MA']=long_ma
# Calculate Exponential Moving Average (EMA)
ema_50= ti.ema(data['Close'],50)
data['EMA_50'] =ema_50
ema_200= ti.ema(data['Close'],200)
data['EMA_200'] =ema_200
# Calculate Relative Strength Index (RSI)
rsi_14 = ti.rsi(data['Close'])
data['RSI_14']=rsi_14
# Calculate Moving Average Convergence Divergence (MACD)
macd = ti.macd(data['Close'])
data['MACD'] = macd
# Calculate Average Directional Index (ADX)
adx_14 = ti.adx(data['High'], data['Low'], data['Close'], 14)
data['ADX_14']=adx_14

In [103]:
#print(data[['Close', 'SMA_20', 'EMA_50', 'RSI_14', 'MACD', 'ADX_14']])

In [104]:
close_price= data['Close']
print(close_price.shape)
close_price

(1481,)

Date
2018-01-01     927.250000
2018-01-02     936.174988
2018-01-03     926.325012
2018-01-04     929.950012
2018-01-05     931.799988
                 ...
2023-12-22    1670.849976
2023-12-26    1682.449951
2023-12-27    1703.300049
2023-12-28    1705.250000
2023-12-29    1709.250000
Name: Close, Length: 1481, dtype: float64

In [105]:
close_prices_reset_index = close_price.reset_index(drop=True)
close_prices_reset_index

0        927.250000
1        936.174988
2        926.325012
3        929.950012
4        931.799988
           ...
1476    1670.849976
1477    1682.449951
1478    1703.300049
1479    1705.250000
1480    1709.250000
Name: Close, Length: 1481, dtype: float64

In [106]:
#print(close_prices_reset_index)

In [107]:
# 1. Normalization (Min-Max Scaling)
min_price = close_prices_reset_index.min()
max_price = close_prices_reset_index.max()
normalized_prices = (close_prices_reset_index - min_price) / (max_price - min_price)

print(min_price)
print(max_price)
print(normalized_prices)

767.7000122070312
1728.199951171875
0       0.166111
1       0.175403
2       0.165148
3       0.168922
4       0.170849
          ...
1476    0.940292
1477    0.952369
1478    0.974076
1479    0.976106
1480    0.980271
Name: Close, Length: 1481, dtype: float64

In [108]:
# 2.percentage change
percentage_change = close_prices_reset_index.pct_change()
percentage_change

0            NaN
1       0.009625
2      -0.010522
3       0.003913
4       0.001989
          ...
1476   -0.009397
1477    0.006943
1478    0.012393
1479    0.001145
1480    0.002346
Name: Close, Length: 1481, dtype: float64

In [109]:
data['Normalized_Prices'] = normalized_prices
data['percentage_change'] = percentage_change

In [110]:
print(data.head())

                  Open        High         Low       Close   Adj Close  \
Date
2018-01-01  936.349976  940.375000  925.250000  927.250000  889.052124
2018-01-02  929.275024  937.500000  929.275024  936.174988  897.609497
2018-01-03  937.500000  939.125000  925.599976  926.325012  888.165283
2018-01-04  926.500000  932.750000  926.500000  929.950012  891.640991
2018-01-05  931.500000  934.025024  927.775024  931.799988  893.414795

             Volume  Tick_Size  Short_MA  Long_MA     EMA_50    EMA_200  \
Date
2018-01-01  3290258  15.125000       NaN      NaN  10.774726   2.697078
2018-01-02  2388158   8.224976       NaN      NaN  21.875313   5.433704
2018-01-03  2265644  13.525024       NaN      NaN  33.090312   8.155466
2018-01-04  1186888   6.250000       NaN      NaN  44.578663  10.901483
2018-01-05  1435434   6.250000       NaN      NaN  56.325375  13.666715

               RSI_14        MACD  ADX_14  Normalized_Prices  \
Date
2018-01-01  77.614473   22.416370     NaN                NaN
2018-01-02  77.614473   46.497390     NaN                NaN
2018-01-03  77.614473   71.671120     NaN                NaN
2018-01-04  77.614473   98.058863     NaN                NaN
2018-01-05  77.614473  125.368020     NaN                NaN

            percentage_change
Date
2018-01-01                NaN
2018-01-02                NaN
2018-01-03                NaN
2018-01-04                NaN
2018-01-05                NaN

In [111]:
indicators_df = pd.DataFrame({
    'Close': data['Close'],
    'Short_MA':short_ma,
    'Long_MA': long_ma,
    'EMA_50': ema_50,
    'EMA_200': ema_200,
    'RSI_14': rsi_14,
    'MACD': macd,
    'ADX_14': adx_14
})

In [112]:
def generate_signals(df):
    signals = []
    for i in range(len(df)):
        if df['Short_MA'].iloc[i] > df['Long_MA'].iloc[i] and \
           df['EMA_50'].iloc[i] > df['EMA_200'].iloc[i] and \
           df['RSI_14'].iloc[i] > 50 and \
           df['MACD'].iloc[i] > 0 and \
           df['ADX_14'].iloc[i] > 25:                               # This is only for the stringth of the
            signals.append('Buy')
        # If sma becomes lesser than lma, then, stock should be preferably sold
        elif (df['Short_MA'].iloc[i] < df['Long_MA'].iloc[i] or \
             df['EMA_50'].iloc[i] < df['EMA_200'].iloc[i]  and \
             df['ADX_14'].iloc[i] > 25) or \
             (df['RSI_14'].iloc[i] < 50 and \
             df['ADX_14'].iloc[i] > 25) or \
             (df['MACD'].iloc[i] < 0 and \
             df['ADX_14'].iloc[i] > 25):     # Strong trend
            signals.append('Sell')
        else:
            signals.append('Hold')
    return signals
# Generate signals
indicators_df['Signal'] = generate_signals(indicators_df)

indicators_df

# def generate_signals(df):
#     signals = []
#     for i in range(len(df)):
#         # Updated conditions for Buy signal
#         if (df['Short_MA'].iloc[i] > df['Long_MA'].iloc[i] and \
#             df['EMA_50'].iloc[i] > df['EMA_200'].iloc[i] and \
#             df['RSI_14'].iloc[i] > 50 and \
#             df['MACD'].iloc[i] > 0 and \
#             df['ADX_14'].iloc[i] > 25):
#             signals.append('Buy')
#         # Updated conditions for Sell signal
#         elif ((df['Short_MA'].iloc[i] < df['Long_MA'].iloc[i] or \
#                df['EMA_50'].iloc[i] < df['EMA_200'].iloc[i]) and \
#               df['ADX_14'].iloc[i] > 25) or \
#               (df['RSI_14'].iloc[i] < 50 and df['ADX_14'].iloc[i] > 25) or \
#               (df['MACD'].iloc[i] < 0 and df['ADX_14'].iloc[i] > 25):
#               signals.append('Sell')
#         else:
#             signals.append('Hold')
#     return signals

# # Generate signals
# indicators_df['Signal'] = generate_signals(indicators_df)

# indicators_df

,Close,Short_MA,Long_MA,EMA_50,EMA_200,RSI_14,MACD,ADX_14,Signal
Date,,,,,,,,,
2018-01-01,927.250000,NaN,NaN,10.774726,2.697078,77.614473,22.416370,NaN,Hold
2018-01-02,936.174988,NaN,NaN,21.875313,5.433704,77.614473,46.497390,NaN,Hold
2018-01-03,926.325012,NaN,NaN,33.090312,8.155466,77.614473,71.671120,NaN,Hold
2018-01-04,929.950012,NaN,NaN,44.578663,10.901483,77.614473,98.058863,NaN,Hold
2018-01-05,931.799988,NaN,NaN,56.325375,13.666715,77.614473,125.368020,NaN,Hold
...,...,...,...,...,...,...,...,...,...
2023-12-22,1670.849976,1621.250000,1550.486001,1536.547529,1611.407370,71.459432,4.010919,69.223980,Sell
2023-12-26,1682.449951,1628.767499,1553.343000,1538.144524,1611.720154,73.561128,-0.998470,66.763629,Sell
2023-12-27,1703.300049,1637.500000,1556.412002,1539.686286,1612.203233,76.859607,-7.912313,65.030711,Sell
2023-12-28,1705.250000,1644.804999,1559.802002,1541.737049,1612.444500,77.146764,-13.076887,63.783072,Sell
2023-12-29,1709.250000,1652.327496,1563.395002,1544.074838,1612.608028,77.756541,-14.305976,60.330731,Sell

In [113]:
print(indicators_df )

                  Close     Short_MA      Long_MA       EMA_50      EMA_200  \
Date
2018-01-01   927.250000          NaN          NaN    10.774726     2.697078
2018-01-02   936.174988          NaN          NaN    21.875313     5.433704
2018-01-03   926.325012          NaN          NaN    33.090312     8.155466
2018-01-04   929.950012          NaN          NaN    44.578663    10.901483
2018-01-05   931.799988          NaN          NaN    56.325375    13.666715
...                 ...          ...          ...          ...          ...
2023-12-22  1670.849976  1621.250000  1550.486001  1536.547529  1611.407370
2023-12-26  1682.449951  1628.767499  1553.343000  1538.144524  1611.720154
2023-12-27  1703.300049  1637.500000  1556.412002  1539.686286  1612.203233
2023-12-28  1705.250000  1644.804999  1559.802002  1541.737049  1612.444500
2023-12-29  1709.250000  1652.327496  1563.395002  1544.074838  1612.608028

               RSI_14        MACD     ADX_14 Signal
Date
2018-01-01  77.614473   22.416370        NaN   Hold
2018-01-02  77.614473   46.497390        NaN   Hold
2018-01-03  77.614473   71.671120        NaN   Hold
2018-01-04  77.614473   98.058863        NaN   Hold
2018-01-05  77.614473  125.368020        NaN   Hold
...               ...         ...        ...    ...
2023-12-22  71.459432    4.010919  69.223980   Sell
2023-12-26  73.561128   -0.998470  66.763629   Sell
2023-12-27  76.859607   -7.912313  65.030711   Sell
2023-12-28  77.146764  -13.076887  63.783072   Sell
2023-12-29  77.756541  -14.305976  60.330731   Sell

[1481 rows x 9 columns]

### Now, we have to train, test and implement the logistic regresion model

In [114]:
indicators_df

,Close,Short_MA,Long_MA,EMA_50,EMA_200,RSI_14,MACD,ADX_14,Signal
Date,,,,,,,,,
2018-01-01,927.250000,NaN,NaN,10.774726,2.697078,77.614473,22.416370,NaN,Hold
2018-01-02,936.174988,NaN,NaN,21.875313,5.433704,77.614473,46.497390,NaN,Hold
2018-01-03,926.325012,NaN,NaN,33.090312,8.155466,77.614473,71.671120,NaN,Hold
2018-01-04,929.950012,NaN,NaN,44.578663,10.901483,77.614473,98.058863,NaN,Hold
2018-01-05,931.799988,NaN,NaN,56.325375,13.666715,77.614473,125.368020,NaN,Hold
...,...,...,...,...,...,...,...,...,...
2023-12-22,1670.849976,1621.250000,1550.486001,1536.547529,1611.407370,71.459432,4.010919,69.223980,Sell
2023-12-26,1682.449951,1628.767499,1553.343000,1538.144524,1611.720154,73.561128,-0.998470,66.763629,Sell
2023-12-27,1703.300049,1637.500000,1556.412002,1539.686286,1612.203233,76.859607,-7.912313,65.030711,Sell
2023-12-28,1705.250000,1644.804999,1559.802002,1541.737049,1612.444500,77.146764,-13.076887,63.783072,Sell
2023-12-29,1709.250000,1652.327496,1563.395002,1544.074838,1612.608028,77.756541,-14.305976,60.330731,Sell

In [115]:
from sklearn.linear_model import LogisticRegression

In [116]:
# On doing proper analysis of the data, we can find that the EMA_200 would contain NaN values 
# until the number of days becomes 200. So, it should be better to drop the column.

x_train = indicators_df[indicators_df.index.year < 2022][["Close", "Short_MA", "Long_MA", "EMA_50", "RSI_14", "MACD", "ADX_14"]]
y_train = indicators_df[indicators_df.index.year < 2022][["Signal"]]
x_test = indicators_df[indicators_df.index.year >= 2022][["Close", "Short_MA", "Long_MA", "EMA_50", "RSI_14", "MACD", "ADX_14"]]
y_test = indicators_df[indicators_df.index.year >= 2022][["Signal"]]

In [117]:
y_test

           Signal
Date
2022-01-03   Sell
2022-01-04   Sell
2022-01-05   Sell
2022-01-06   Sell
2022-01-07   Sell
...           ...
2023-12-22   Sell
2023-12-26   Sell
2023-12-27   Sell
2023-12-28   Sell
2023-12-29   Sell

[493 rows x 1 columns]

In [118]:
y_train

           Signal
Date
2018-01-01   Hold
2018-01-02   Hold
2018-01-03   Hold
2018-01-04   Hold
2018-01-05   Hold
...           ...
2021-12-27   Sell
2021-12-28   Sell
2021-12-29   Sell
2021-12-30   Sell
2021-12-31   Sell

[988 rows x 1 columns]

In [119]:
x_train

,Close,Short_MA,Long_MA,EMA_50,RSI_14,MACD,ADX_14
Date,,,,,,,
2018-01-01,927.250000,NaN,NaN,10.774726,77.614473,22.416370,NaN
2018-01-02,936.174988,NaN,NaN,21.875313,77.614473,46.497390,NaN
2018-01-03,926.325012,NaN,NaN,33.090312,77.614473,71.671120,NaN
2018-01-04,929.950012,NaN,NaN,44.578663,77.614473,98.058863,NaN
2018-01-05,931.799988,NaN,NaN,56.325375,77.614473,125.368020,NaN
...,...,...,...,...,...,...,...
2021-12-27,1450.800049,1490.170013,1549.354009,1569.203320,36.926893,-9.943922,18.068227
2021-12-28,1460.800049,1488.532513,1544.822009,1564.133248,40.372225,-14.996934,22.042354
2021-12-29,1453.849976,1485.992511,1540.493008,1559.429150,38.786452,-17.764208,25.670231
2021-12-30,1461.500000,1482.780011,1535.949009,1554.123783,41.509778,-18.514213,28.678555
2021-12-31,1479.400024,1481.072510,1532.060010,1549.395763,47.405877,-18.276841,30.709263

In [120]:
x_test

,Close,Short_MA,Long_MA,EMA_50,RSI_14,MACD,ADX_14
Date,,,,,,,
2022-01-03,1519.650024,1481.865009,1528.927009,1544.958984,57.725368,-19.015894,31.144194
2022-01-04,1528.550049,1482.007513,1525.883010,1540.390691,59.612399,-14.540824,31.044338
2022-01-05,1564.849976,1482.560010,1524.040010,1536.915668,66.232918,-3.153697,30.603871
2022-01-06,1539.750000,1483.205011,1521.780010,1533.214345,59.027627,5.328710,31.357609
2022-01-07,1550.550049,1484.605011,1519.935010,1529.882973,60.993915,14.532704,35.163105
...,...,...,...,...,...,...,...
2023-12-22,1670.849976,1621.250000,1550.486001,1536.547529,71.459432,4.010919,69.223980
2023-12-26,1682.449951,1628.767499,1553.343000,1538.144524,73.561128,-0.998470,66.763629
2023-12-27,1703.300049,1637.500000,1556.412002,1539.686286,76.859607,-7.912313,65.030711
2023-12-28,1705.250000,1644.804999,1559.802002,1541.737049,77.146764,-13.076887,63.783072
2023-12-29,1709.250000,1652.327496,1563.395002,1544.074838,77.756541,-14.305976,60.330731

In [121]:
file_path = 'data.csv'

In [122]:
indicators_df.to_csv(file_path, index=False)

In [123]:
excel_file_path = 'output.xlsx'

In [124]:
indicators_df.to_excel(excel_file_path, index=False)

In [125]:
# Now, the column of EMA_200 is removed. Now we will remove the rows containing NaN values. 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [126]:
# Prepare the data
x_train = x_train.dropna()  # Remove rows with NaN values
y_train = y_train.loc[x_train.index]
x_test = x_test.dropna()  # Remove rows with NaN values
y_test = y_test.loc[x_test.index]

In [127]:
# Instantiate the logistic regression model
model = LogisticRegression()

In [128]:
# Fit the model to the training data
model.fit(x_train, y_train)

c:\Users\ANSHUMAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ANSHUMAN\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [129]:
# Predict the target values for the test data
y_pred = model.predict(x_test)
# Assuming x_test contains dates as index
predictions_dict = dict(zip(x_test.index, y_pred))

In [130]:
y_pred

array(['Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Hold', 'Hold', 'Sell', 'Hold', 'Hold',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Buy', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Sell', 'Sell', 'Sell', 'Sell',
       'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Buy', 'Buy',
       'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy',
       'Buy', 'Sell', 'Sell', 'Sell', 'Sell', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Hold',
       'Hold', 'Hold', 'Hold', 'Hold', 'Hold', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell',
       'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Sell', 'Buy',
       'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Buy', 'Sell',
       'Sell', 'Sell'], dtype=object)

In [131]:
predictions_dict

{Timestamp('2022-01-03 00:00:00'): 'Sell',
 Timestamp('2022-01-04 00:00:00'): 'Sell',
 Timestamp('2022-01-05 00:00:00'): 'Sell',
 Timestamp('2022-01-06 00:00:00'): 'Sell',
 Timestamp('2022-01-07 00:00:00'): 'Sell',
 Timestamp('2022-01-10 00:00:00'): 'Sell',
 Timestamp('2022-01-11 00:00:00'): 'Sell',
 Timestamp('2022-01-12 00:00:00'): 'Sell',
 Timestamp('2022-01-13 00:00:00'): 'Sell',
 Timestamp('2022-01-14 00:00:00'): 'Sell',
 Timestamp('2022-01-17 00:00:00'): 'Sell',
 Timestamp('2022-01-18 00:00:00'): 'Sell',
 Timestamp('2022-01-19 00:00:00'): 'Sell',
 Timestamp('2022-01-20 00:00:00'): 'Sell',
 Timestamp('2022-01-21 00:00:00'): 'Sell',
 Timestamp('2022-01-24 00:00:00'): 'Sell',
 Timestamp('2022-01-25 00:00:00'): 'Sell',
 Timestamp('2022-01-27 00:00:00'): 'Sell',
 Timestamp('2022-01-28 00:00:00'): 'Sell',
 Timestamp('2022-01-31 00:00:00'): 'Sell',
 Timestamp('2022-02-01 00:00:00'): 'Sell',
 Timestamp('2022-02-02 00:00:00'): 'Sell',
 Timestamp('2022-02-03 00:00:00'): 'Sell',
 Timestamp('2022-02-04 00:00:00'): 'Sell',
 Timestamp('2022-02-07 00:00:00'): 'Sell',
 Timestamp('2022-02-08 00:00:00'): 'Sell',
 Timestamp('2022-02-09 00:00:00'): 'Sell',
 Timestamp('2022-02-10 00:00:00'): 'Sell',
 Timestamp('2022-02-11 00:00:00'): 'Sell',
 Timestamp('2022-02-14 00:00:00'): 'Sell',
 Timestamp('2022-02-15 00:00:00'): 'Sell',
 Timestamp('2022-02-16 00:00:00'): 'Sell',
 Timestamp('2022-02-17 00:00:00'): 'Sell',
 Timestamp('2022-02-18 00:00:00'): 'Sell',
 Timestamp('2022-02-21 00:00:00'): 'Sell',
 Timestamp('2022-02-22 00:00:00'): 'Hold',
 Timestamp('2022-02-23 00:00:00'): 'Hold',
 Timestamp('2022-02-24 00:00:00'): 'Sell',
 Timestamp('2022-02-25 00:00:00'): 'Hold',
 Timestamp('2022-02-28 00:00:00'): 'Hold',
 Timestamp('2022-03-02 00:00:00'): 'Sell',
 Timestamp('2022-03-03 00:00:00'): 'Sell',
 Timestamp('2022-03-04 00:00:00'): 'Sell',
 Timestamp('2022-03-07 00:00:00'): 'Sell',
 Timestamp('2022-03-08 00:00:00'): 'Sell',
 Timestamp('2022-03-09 00:00:00'): 'Sell',
 Timestamp('2022-03-10 00:00:00'): 'Sell',
 Timestamp('2022-03-11 00:00:00'): 'Sell',
 Timestamp('2022-03-14 00:00:00'): 'Sell',
 Timestamp('2022-03-15 00:00:00'): 'Sell',
 Timestamp('2022-03-16 00:00:00'): 'Sell',
 Timestamp('2022-03-17 00:00:00'): 'Sell',
 Timestamp('2022-03-21 00:00:00'): 'Sell',
 Timestamp('2022-03-22 00:00:00'): 'Sell',
 Timestamp('2022-03-23 00:00:00'): 'Sell',
 Timestamp('2022-03-24 00:00:00'): 'Sell',
 Timestamp('2022-03-25 00:00:00'): 'Sell',
 Timestamp('2022-03-28 00:00:00'): 'Sell',
 Timestamp('2022-03-29 00:00:00'): 'Sell',
 Timestamp('2022-03-30 00:00:00'): 'Sell',
 Timestamp('2022-03-31 00:00:00'): 'Sell',
 Timestamp('2022-04-01 00:00:00'): 'Sell',
 Timestamp('2022-04-04 00:00:00'): 'Buy',
 Timestamp('2022-04-05 00:00:00'): 'Sell',
 Timestamp('2022-04-06 00:00:00'): 'Sell',
 Timestamp('2022-04-07 00:00:00'): 'Sell',
 Timestamp('2022-04-08 00:00:00'): 'Sell',
 Timestamp('2022-04-11 00:00:00'): 'Sell',
 Timestamp('2022-04-12 00:00:00'): 'Sell',
 Timestamp('2022-04-13 00:00:00'): 'Sell',
 Timestamp('2022-04-18 00:00:00'): 'Sell',
 Timestamp('2022-04-19 00:00:00'): 'Sell',
 Timestamp('2022-04-20 00:00:00'): 'Sell',
 Timestamp('2022-04-21 00:00:00'): 'Sell',
 Timestamp('2022-04-22 00:00:00'): 'Sell',
 Timestamp('2022-04-25 00:00:00'): 'Sell',
 Timestamp('2022-04-26 00:00:00'): 'Sell',
 Timestamp('2022-04-27 00:00:00'): 'Sell',
 Timestamp('2022-04-28 00:00:00'): 'Sell',
 Timestamp('2022-04-29 00:00:00'): 'Sell',
 Timestamp('2022-05-02 00:00:00'): 'Sell',
 Timestamp('2022-05-04 00:00:00'): 'Sell',
 Timestamp('2022-05-05 00:00:00'): 'Sell',
 Timestamp('2022-05-06 00:00:00'): 'Sell',
 Timestamp('2022-05-09 00:00:00'): 'Sell',
 Timestamp('2022-05-10 00:00:00'): 'Sell',
 Timestamp('2022-05-11 00:00:00'): 'Sell',
 Timestamp('2022-05-12 00:00:00'): 'Sell',
 Timestamp('2022-05-13 00:00:00'): 'Sell',
 Timestamp('2022-05-16 00:00:00'): 'Sell',
 Timestamp('2022-05-17 00:00:00'): 'Sell',
 Timestamp('2022-05-18 00:00:00'): 'Sell',
 Timestamp('2022-05-19 00:00:00'): 'Sell',
 Timestamp('2022-05-20 00:00:00'): 'Sell',
 Timestamp('2022-05-23 00:00:00'): 'Sell',
 Timestamp('2022-05-24 00:00:00'): 'Sell',
 Timestamp('2022-05-25 00:00:00'): 'Sell',
 Timestamp('2022-05-26 00:00:00'): 'Sell',
 Timestamp('2022-05-27 00:00:00'): 'Sell',
 Timestamp('2022-05-30 00:00:00'): 'Sell',
 Timestamp('2022-05-31 00:00:00'): 'Sell',
 Timestamp('2022-06-01 00:00:00'): 'Sell',
 Timestamp('2022-06-02 00:00:00'): 'Sell',
 Timestamp('2022-06-03 00:00:00'): 'Sell',
 Timestamp('2022-06-06 00:00:00'): 'Sell',
 Timestamp('2022-06-07 00:00:00'): 'Sell',
 Timestamp('2022-06-08 00:00:00'): 'Sell',
 Timestamp('2022-06-09 00:00:00'): 'Sell',
 Timestamp('2022-06-10 00:00:00'): 'Sell',
 Timestamp('2022-06-13 00:00:00'): 'Sell',
 Timestamp('2022-06-14 00:00:00'): 'Sell',
 Timestamp('2022-06-15 00:00:00'): 'Sell',
 Timestamp('2022-06-16 00:00:00'): 'Sell',
 Timestamp('2022-06-17 00:00:00'): 'Sell',
 Timestamp('2022-06-20 00:00:00'): 'Sell',
 Timestamp('2022-06-21 00:00:00'): 'Sell',
 Timestamp('2022-06-22 00:00:00'): 'Sell',
 Timestamp('2022-06-23 00:00:00'): 'Sell',
 Timestamp('2022-06-24 00:00:00'): 'Sell',
 Timestamp('2022-06-27 00:00:00'): 'Sell',
 Timestamp('2022-06-28 00:00:00'): 'Sell',
 Timestamp('2022-06-29 00:00:00'): 'Sell',
 Timestamp('2022-06-30 00:00:00'): 'Sell',
 Timestamp('2022-07-01 00:00:00'): 'Sell',
 Timestamp('2022-07-04 00:00:00'): 'Sell',
 Timestamp('2022-07-05 00:00:00'): 'Sell',
 Timestamp('2022-07-06 00:00:00'): 'Sell',
 Timestamp('2022-07-07 00:00:00'): 'Sell',
 Timestamp('2022-07-08 00:00:00'): 'Sell',
 Timestamp('2022-07-11 00:00:00'): 'Sell',
 Timestamp('2022-07-12 00:00:00'): 'Sell',
 Timestamp('2022-07-13 00:00:00'): 'Sell',
 Timestamp('2022-07-14 00:00:00'): 'Sell',
 Timestamp('2022-07-15 00:00:00'): 'Sell',
 Timestamp('2022-07-18 00:00:00'): 'Sell',
 Timestamp('2022-07-19 00:00:00'): 'Sell',
 Timestamp('2022-07-20 00:00:00'): 'Sell',
 Timestamp('2022-07-21 00:00:00'): 'Sell',
 Timestamp('2022-07-22 00:00:00'): 'Sell',
 Timestamp('2022-07-25 00:00:00'): 'Sell',
 Timestamp('2022-07-26 00:00:00'): 'Sell',
 Timestamp('2022-07-27 00:00:00'): 'Sell',
 Timestamp('2022-07-28 00:00:00'): 'Hold',
 Timestamp('2022-07-29 00:00:00'): 'Hold',
 Timestamp('2022-08-01 00:00:00'): 'Hold',
 Timestamp('2022-08-02 00:00:00'): 'Hold',
 Timestamp('2022-08-03 00:00:00'): 'Hold',
 Timestamp('2022-08-04 00:00:00'): 'Hold',
 Timestamp('2022-08-05 00:00:00'): 'Sell',
 Timestamp('2022-08-08 00:00:00'): 'Sell',
 Timestamp('2022-08-10 00:00:00'): 'Sell',
 Timestamp('2022-08-11 00:00:00'): 'Sell',
 Timestamp('2022-08-12 00:00:00'): 'Buy',
 Timestamp('2022-08-16 00:00:00'): 'Buy',
 Timestamp('2022-08-17 00:00:00'): 'Buy',
 Timestamp('2022-08-18 00:00:00'): 'Buy',
 Timestamp('2022-08-19 00:00:00'): 'Buy',
 Timestamp('2022-08-22 00:00:00'): 'Buy',
 Timestamp('2022-08-23 00:00:00'): 'Buy',
 Timestamp('2022-08-24 00:00:00'): 'Buy',
 Timestamp('2022-08-25 00:00:00'): 'Buy',
 Timestamp('2022-08-26 00:00:00'): 'Sell',
 Timestamp('2022-08-29 00:00:00'): 'Sell',
 Timestamp('2022-08-30 00:00:00'): 'Sell',
 Timestamp('2022-09-01 00:00:00'): 'Sell',
 Timestamp('2022-09-02 00:00:00'): 'Sell',
 Timestamp('2022-09-05 00:00:00'): 'Sell',
 Timestamp('2022-09-06 00:00:00'): 'Hold',
 Timestamp('2022-09-07 00:00:00'): 'Hold',
 Timestamp('2022-09-08 00:00:00'): 'Hold',
 Timestamp('2022-09-09 00:00:00'): 'Hold',
 Timestamp('2022-09-12 00:00:00'): 'Hold',
 Timestamp('2022-09-13 00:00:00'): 'Hold',
 Timestamp('2022-09-14 00:00:00'): 'Hold',
 Timestamp('2022-09-15 00:00:00'): 'Hold',
 Timestamp('2022-09-16 00:00:00'): 'Hold',
 Timestamp('2022-09-19 00:00:00'): 'Hold',
 Timestamp('2022-09-20 00:00:00'): 'Hold',
 Timestamp('2022-09-21 00:00:00'): 'Hold',
 Timestamp('2022-09-22 00:00:00'): 'Hold',
 Timestamp('2022-09-23 00:00:00'): 'Hold',
 Timestamp('2022-09-26 00:00:00'): 'Hold',
 Timestamp('2022-09-27 00:00:00'): 'Hold',
 Timestamp('2022-09-28 00:00:00'): 'Sell',
 Timestamp('2022-09-29 00:00:00'): 'Sell',
 Timestamp('2022-09-30 00:00:00'): 'Sell',
 Timestamp('2022-10-03 00:00:00'): 'Sell',
 Timestamp('2022-10-04 00:00:00'): 'Sell',
 Timestamp('2022-10-06 00:00:00'): 'Sell',
 Timestamp('2022-10-07 00:00:00'): 'Sell',
 Timestamp('2022-10-10 00:00:00'): 'Sell',
 Timestamp('2022-10-11 00:00:00'): 'Sell',
 Timestamp('2022-10-12 00:00:00'): 'Sell',
 Timestamp('2022-10-13 00:00:00'): 'Sell',
 Timestamp('2022-10-14 00:00:00'): 'Sell',
 Timestamp('2022-10-17 00:00:00'): 'Sell',
 Timestamp('2022-10-18 00:00:00'): 'Sell',
 Timestamp('2022-10-19 00:00:00'): 'Sell',
 Timestamp('2022-10-20 00:00:00'): 'Sell',
 Timestamp('2022-10-21 00:00:00'): 'Sell',
 Timestamp('2022-10-24 00:00:00'): 'Sell',
 Timestamp('2022-10-25 00:00:00'): 'Sell',
 Timestamp('2022-10-27 00:00:00'): 'Sell',
 Timestamp('2022-10-28 00:00:00'): 'Sell',
 Timestamp('2022-10-31 00:00:00'): 'Sell',
 Timestamp('2022-11-01 00:00:00'): 'Sell',
 Timestamp('2022-11-02 00:00:00'): 'Sell',
 Timestamp('2022-11-03 00:00:00'): 'Sell',
 Timestamp('2022-11-04 00:00:00'): 'Sell',
 Timestamp('2022-11-07 00:00:00'): 'Sell',
 Timestamp('2022-11-09 00:00:00'): 'Sell',
 Timestamp('2022-11-10 00:00:00'): 'Sell',
 Timestamp('2022-11-11 00:00:00'): 'Sell',
 Timestamp('2022-11-14 00:00:00'): 'Sell',
 Timestamp('2022-11-15 00:00:00'): 'Sell',
 Timestamp('2022-11-16 00:00:00'): 'Buy',
 Timestamp('2022-11-17 00:00:00'): 'Buy',
 Timestamp('2022-11-18 00:00:00'): 'Buy',
 Timestamp('2022-11-21 00:00:00'): 'Buy',
 Timestamp('2022-11-22 00:00:00'): 'Buy',
 Timestamp('2022-11-23 00:00:00'): 'Buy',
 Timestamp('2022-11-24 00:00:00'): 'Buy',
 Timestamp('2022-11-25 00:00:00'): 'Buy',
 Timestamp('2022-11-28 00:00:00'): 'Buy',
 Timestamp('2022-11-29 00:00:00'): 'Buy',
 Timestamp('2022-11-30 00:00:00'): 'Buy',
 Timestamp('2022-12-01 00:00:00'): 'Buy',
 Timestamp('2022-12-02 00:00:00'): 'Sell',
 Timestamp('2022-12-05 00:00:00'): 'Sell',
 Timestamp('2022-12-06 00:00:00'): 'Sell',
 Timestamp('2022-12-07 00:00:00'): 'Sell',
 Timestamp('2022-12-08 00:00:00'): 'Hold',
 Timestamp('2022-12-09 00:00:00'): 'Hold',
 Timestamp('2022-12-12 00:00:00'): 'Hold',
 Timestamp('2022-12-13 00:00:00'): 'Hold',
 Timestamp('2022-12-14 00:00:00'): 'Hold',
 Timestamp('2022-12-15 00:00:00'): 'Hold',
 Timestamp('2022-12-16 00:00:00'): 'Hold',
 Timestamp('2022-12-19 00:00:00'): 'Hold',
 Timestamp('2022-12-20 00:00:00'): 'Hold',
 Timestamp('2022-12-21 00:00:00'): 'Hold',
 Timestamp('2022-12-22 00:00:00'): 'Hold',
 Timestamp('2022-12-23 00:00:00'): 'Hold',
 Timestamp('2022-12-26 00:00:00'): 'Hold',
 Timestamp('2022-12-27 00:00:00'): 'Hold',
 Timestamp('2022-12-28 00:00:00'): 'Hold',
 Timestamp('2022-12-29 00:00:00'): 'Hold',
 Timestamp('2022-12-30 00:00:00'): 'Hold',
 Timestamp('2023-01-02 00:00:00'): 'Hold',
 Timestamp('2023-01-03 00:00:00'): 'Hold',
 Timestamp('2023-01-04 00:00:00'): 'Hold',
 Timestamp('2023-01-05 00:00:00'): 'Hold',
 Timestamp('2023-01-06 00:00:00'): 'Hold',
 Timestamp('2023-01-09 00:00:00'): 'Sell',
 Timestamp('2023-01-10 00:00:00'): 'Sell',
 Timestamp('2023-01-11 00:00:00'): 'Sell',
 Timestamp('2023-01-12 00:00:00'): 'Sell',
 Timestamp('2023-01-13 00:00:00'): 'Sell',
 Timestamp('2023-01-16 00:00:00'): 'Sell',
 Timestamp('2023-01-17 00:00:00'): 'Sell',
 Timestamp('2023-01-18 00:00:00'): 'Sell',
 Timestamp('2023-01-19 00:00:00'): 'Sell',
 Timestamp('2023-01-20 00:00:00'): 'Sell',
 Timestamp('2023-01-23 00:00:00'): 'Sell',
 Timestamp('2023-01-24 00:00:00'): 'Sell',
 Timestamp('2023-01-25 00:00:00'): 'Sell',
 Timestamp('2023-01-27 00:00:00'): 'Sell',
 Timestamp('2023-01-30 00:00:00'): 'Sell',
 Timestamp('2023-01-31 00:00:00'): 'Sell',
 Timestamp('2023-02-01 00:00:00'): 'Sell',
 Timestamp('2023-02-02 00:00:00'): 'Sell',
 Timestamp('2023-02-03 00:00:00'): 'Hold',
 Timestamp('2023-02-06 00:00:00'): 'Hold',
 Timestamp('2023-02-07 00:00:00'): 'Hold',
 Timestamp('2023-02-08 00:00:00'): 'Hold',
 Timestamp('2023-02-09 00:00:00'): 'Hold',
 Timestamp('2023-02-10 00:00:00'): 'Hold',
 Timestamp('2023-02-13 00:00:00'): 'Hold',
 Timestamp('2023-02-14 00:00:00'): 'Hold',
 Timestamp('2023-02-15 00:00:00'): 'Hold',
 Timestamp('2023-02-16 00:00:00'): 'Hold',
 Timestamp('2023-02-17 00:00:00'): 'Hold',
 Timestamp('2023-02-20 00:00:00'): 'Hold',
 Timestamp('2023-02-21 00:00:00'): 'Hold',
 Timestamp('2023-02-22 00:00:00'): 'Hold',
 Timestamp('2023-02-23 00:00:00'): 'Hold',
 Timestamp('2023-02-24 00:00:00'): 'Hold',
 Timestamp('2023-02-27 00:00:00'): 'Sell',
 Timestamp('2023-02-28 00:00:00'): 'Sell',
 Timestamp('2023-03-01 00:00:00'): 'Sell',
 Timestamp('2023-03-02 00:00:00'): 'Sell',
 Timestamp('2023-03-03 00:00:00'): 'Sell',
 Timestamp('2023-03-06 00:00:00'): 'Sell',
 Timestamp('2023-03-08 00:00:00'): 'Sell',
 Timestamp('2023-03-09 00:00:00'): 'Sell',
 Timestamp('2023-03-10 00:00:00'): 'Sell',
 Timestamp('2023-03-13 00:00:00'): 'Sell',
 Timestamp('2023-03-14 00:00:00'): 'Sell',
 Timestamp('2023-03-15 00:00:00'): 'Sell',
 Timestamp('2023-03-16 00:00:00'): 'Sell',
 Timestamp('2023-03-17 00:00:00'): 'Sell',
 Timestamp('2023-03-20 00:00:00'): 'Sell',
 Timestamp('2023-03-21 00:00:00'): 'Sell',
 Timestamp('2023-03-22 00:00:00'): 'Sell',
 Timestamp('2023-03-23 00:00:00'): 'Sell',
 Timestamp('2023-03-24 00:00:00'): 'Sell',
 Timestamp('2023-03-27 00:00:00'): 'Sell',
 Timestamp('2023-03-28 00:00:00'): 'Sell',
 Timestamp('2023-03-29 00:00:00'): 'Sell',
 Timestamp('2023-03-31 00:00:00'): 'Sell',
 Timestamp('2023-04-03 00:00:00'): 'Sell',
 Timestamp('2023-04-05 00:00:00'): 'Sell',
 Timestamp('2023-04-06 00:00:00'): 'Sell',
 Timestamp('2023-04-10 00:00:00'): 'Sell',
 Timestamp('2023-04-11 00:00:00'): 'Sell',
 Timestamp('2023-04-12 00:00:00'): 'Sell',
 Timestamp('2023-04-13 00:00:00'): 'Sell',
 Timestamp('2023-04-17 00:00:00'): 'Sell',
 Timestamp('2023-04-18 00:00:00'): 'Sell',
 Timestamp('2023-04-19 00:00:00'): 'Sell',
 Timestamp('2023-04-20 00:00:00'): 'Sell',
 Timestamp('2023-04-21 00:00:00'): 'Sell',
 Timestamp('2023-04-24 00:00:00'): 'Sell',
 Timestamp('2023-04-25 00:00:00'): 'Sell',
 Timestamp('2023-04-26 00:00:00'): 'Sell',
 Timestamp('2023-04-27 00:00:00'): 'Sell',
 Timestamp('2023-04-28 00:00:00'): 'Sell',
 Timestamp('2023-05-02 00:00:00'): 'Sell',
 Timestamp('2023-05-03 00:00:00'): 'Sell',
 Timestamp('2023-05-04 00:00:00'): 'Sell',
 Timestamp('2023-05-05 00:00:00'): 'Sell',
 Timestamp('2023-05-08 00:00:00'): 'Sell',
 Timestamp('2023-05-09 00:00:00'): 'Sell',
 Timestamp('2023-05-10 00:00:00'): 'Hold',
 Timestamp('2023-05-11 00:00:00'): 'Hold',
 Timestamp('2023-05-12 00:00:00'): 'Hold',
 Timestamp('2023-05-15 00:00:00'): 'Hold',
 Timestamp('2023-05-16 00:00:00'): 'Hold',
 Timestamp('2023-05-17 00:00:00'): 'Hold',
 Timestamp('2023-05-18 00:00:00'): 'Hold',
 Timestamp('2023-05-19 00:00:00'): 'Hold',
 Timestamp('2023-05-22 00:00:00'): 'Hold',
 Timestamp('2023-05-23 00:00:00'): 'Hold',
 Timestamp('2023-05-24 00:00:00'): 'Hold',
 Timestamp('2023-05-25 00:00:00'): 'Hold',
 Timestamp('2023-05-26 00:00:00'): 'Hold',
 Timestamp('2023-05-29 00:00:00'): 'Hold',
 Timestamp('2023-05-30 00:00:00'): 'Hold',
 Timestamp('2023-05-31 00:00:00'): 'Hold',
 Timestamp('2023-06-01 00:00:00'): 'Sell',
 Timestamp('2023-06-02 00:00:00'): 'Sell',
 Timestamp('2023-06-05 00:00:00'): 'Sell',
 Timestamp('2023-06-06 00:00:00'): 'Sell',
 Timestamp('2023-06-07 00:00:00'): 'Sell',
 Timestamp('2023-06-08 00:00:00'): 'Sell',
 Timestamp('2023-06-09 00:00:00'): 'Sell',
 Timestamp('2023-06-12 00:00:00'): 'Sell',
 Timestamp('2023-06-13 00:00:00'): 'Sell',
 Timestamp('2023-06-14 00:00:00'): 'Sell',
 Timestamp('2023-06-15 00:00:00'): 'Sell',
 Timestamp('2023-06-16 00:00:00'): 'Sell',
 Timestamp('2023-06-19 00:00:00'): 'Sell',
 Timestamp('2023-06-20 00:00:00'): 'Sell',
 Timestamp('2023-06-21 00:00:00'): 'Sell',
 Timestamp('2023-06-22 00:00:00'): 'Sell',
 Timestamp('2023-06-23 00:00:00'): 'Sell',
 Timestamp('2023-06-26 00:00:00'): 'Sell',
 Timestamp('2023-06-27 00:00:00'): 'Sell',
 Timestamp('2023-06-28 00:00:00'): 'Sell',
 Timestamp('2023-06-30 00:00:00'): 'Sell',
 Timestamp('2023-07-03 00:00:00'): 'Sell',
 Timestamp('2023-07-04 00:00:00'): 'Sell',
 Timestamp('2023-07-05 00:00:00'): 'Sell',
 Timestamp('2023-07-06 00:00:00'): 'Sell',
 Timestamp('2023-07-07 00:00:00'): 'Sell',
 Timestamp('2023-07-10 00:00:00'): 'Sell',
 Timestamp('2023-07-11 00:00:00'): 'Sell',
 Timestamp('2023-07-12 00:00:00'): 'Sell',
 Timestamp('2023-07-13 00:00:00'): 'Sell',
 Timestamp('2023-07-14 00:00:00'): 'Sell',
 Timestamp('2023-07-17 00:00:00'): 'Sell',
 Timestamp('2023-07-18 00:00:00'): 'Sell',
 Timestamp('2023-07-19 00:00:00'): 'Sell',
 Timestamp('2023-07-20 00:00:00'): 'Sell',
 Timestamp('2023-07-21 00:00:00'): 'Sell',
 Timestamp('2023-07-24 00:00:00'): 'Hold',
 Timestamp('2023-07-25 00:00:00'): 'Hold',
 Timestamp('2023-07-26 00:00:00'): 'Hold',
 Timestamp('2023-07-27 00:00:00'): 'Hold',
 Timestamp('2023-07-28 00:00:00'): 'Hold',
 Timestamp('2023-07-31 00:00:00'): 'Hold',
 Timestamp('2023-08-01 00:00:00'): 'Hold',
 Timestamp('2023-08-02 00:00:00'): 'Hold',
 Timestamp('2023-08-03 00:00:00'): 'Hold',
 Timestamp('2023-08-04 00:00:00'): 'Hold',
 Timestamp('2023-08-07 00:00:00'): 'Hold',
 Timestamp('2023-08-08 00:00:00'): 'Hold',
 Timestamp('2023-08-09 00:00:00'): 'Hold',
 Timestamp('2023-08-10 00:00:00'): 'Hold',
 Timestamp('2023-08-11 00:00:00'): 'Sell',
 Timestamp('2023-08-14 00:00:00'): 'Sell',
 Timestamp('2023-08-16 00:00:00'): 'Sell',
 Timestamp('2023-08-17 00:00:00'): 'Sell',
 Timestamp('2023-08-18 00:00:00'): 'Sell',
 Timestamp('2023-08-21 00:00:00'): 'Sell',
 Timestamp('2023-08-22 00:00:00'): 'Sell',
 Timestamp('2023-08-23 00:00:00'): 'Sell',
 Timestamp('2023-08-24 00:00:00'): 'Sell',
 Timestamp('2023-08-25 00:00:00'): 'Sell',
 Timestamp('2023-08-28 00:00:00'): 'Sell',
 Timestamp('2023-08-29 00:00:00'): 'Sell',
 Timestamp('2023-08-30 00:00:00'): 'Sell',
 Timestamp('2023-08-31 00:00:00'): 'Sell',
 Timestamp('2023-09-01 00:00:00'): 'Sell',
 Timestamp('2023-09-04 00:00:00'): 'Sell',
 Timestamp('2023-09-05 00:00:00'): 'Sell',
 Timestamp('2023-09-06 00:00:00'): 'Sell',
 Timestamp('2023-09-07 00:00:00'): 'Sell',
 Timestamp('2023-09-08 00:00:00'): 'Sell',
 Timestamp('2023-09-11 00:00:00'): 'Sell',
 Timestamp('2023-09-12 00:00:00'): 'Sell',
 Timestamp('2023-09-13 00:00:00'): 'Sell',
 Timestamp('2023-09-14 00:00:00'): 'Sell',
 Timestamp('2023-09-15 00:00:00'): 'Sell',
 Timestamp('2023-09-18 00:00:00'): 'Sell',
 Timestamp('2023-09-20 00:00:00'): 'Sell',
 Timestamp('2023-09-21 00:00:00'): 'Sell',
 Timestamp('2023-09-22 00:00:00'): 'Sell',
 Timestamp('2023-09-25 00:00:00'): 'Sell',
 Timestamp('2023-09-26 00:00:00'): 'Sell',
 Timestamp('2023-09-27 00:00:00'): 'Sell',
 Timestamp('2023-09-28 00:00:00'): 'Sell',
 Timestamp('2023-09-29 00:00:00'): 'Sell',
 Timestamp('2023-10-03 00:00:00'): 'Sell',
 Timestamp('2023-10-04 00:00:00'): 'Sell',
 Timestamp('2023-10-05 00:00:00'): 'Sell',
 Timestamp('2023-10-06 00:00:00'): 'Sell',
 Timestamp('2023-10-09 00:00:00'): 'Sell',
 Timestamp('2023-10-10 00:00:00'): 'Sell',
 Timestamp('2023-10-11 00:00:00'): 'Sell',
 Timestamp('2023-10-12 00:00:00'): 'Sell',
 Timestamp('2023-10-13 00:00:00'): 'Sell',
 Timestamp('2023-10-16 00:00:00'): 'Sell',
 Timestamp('2023-10-17 00:00:00'): 'Sell',
 Timestamp('2023-10-18 00:00:00'): 'Sell',
 Timestamp('2023-10-19 00:00:00'): 'Sell',
 Timestamp('2023-10-20 00:00:00'): 'Sell',
 Timestamp('2023-10-23 00:00:00'): 'Sell',
 Timestamp('2023-10-25 00:00:00'): 'Sell',
 Timestamp('2023-10-26 00:00:00'): 'Sell',
 Timestamp('2023-10-27 00:00:00'): 'Sell',
 Timestamp('2023-10-30 00:00:00'): 'Sell',
 Timestamp('2023-10-31 00:00:00'): 'Sell',
 Timestamp('2023-11-01 00:00:00'): 'Sell',
 Timestamp('2023-11-02 00:00:00'): 'Sell',
 Timestamp('2023-11-03 00:00:00'): 'Sell',
 Timestamp('2023-11-06 00:00:00'): 'Sell',
 Timestamp('2023-11-07 00:00:00'): 'Sell',
 Timestamp('2023-11-08 00:00:00'): 'Sell',
 Timestamp('2023-11-09 00:00:00'): 'Sell',
 Timestamp('2023-11-10 00:00:00'): 'Sell',
 Timestamp('2023-11-13 00:00:00'): 'Sell',
 Timestamp('2023-11-15 00:00:00'): 'Sell',
 Timestamp('2023-11-16 00:00:00'): 'Sell',
 Timestamp('2023-11-17 00:00:00'): 'Sell',

In [132]:
# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8823529411764706

In [133]:
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

         Buy       0.35      0.41      0.38        27
        Hold       0.86      0.90      0.88        90
        Sell       0.93      0.91      0.92       376

    accuracy                           0.88       493
   macro avg       0.72      0.74      0.73       493
weighted avg       0.89      0.88      0.88       493